#config_version=6
mode_settings:
  selectable_items:
    - title
    - credits
    - mpf_logo
  next_item_events: s_left_flipper_active
  previous_item_events: s_right_flipper_active

slide_player:
  mode_attract_started: attract
sound_player:
  mode_attract_started: 
    slowlife:
      bus:  music
