#config_version=5

switches:
  s_left_flipper:
    number: 31
    tags: left_flipper
  s_right_flipper:
    number: 32
    tags: right_flipper
  s_trough1:
    number: 1
  s_trough2:
    number: 2
  s_trough3:
    number: 3
  s_trough4:
    number: 4
  s_trough5:
    number: 5
  s_trough6:
    number: 6
  s_trough_jam:
    number: 7
  s_plunger_lane:
    number: 10
  s_launch_button:
    number: 30
  s_start:
    number: 33
    tags: start
  s_L_inlane:
    number: 12
    tags: playfield_active
  s_T_inlane:
    number: 13
    tags: playfield_active
  s_M_inlane:
    number: 14
    tags: playfield_active
  s_top_popper:
    number: 15
  s_left_slingshot:
    number: 20
  s_right_slingshot:
    number: 21
  s_left_jet:
    number: 22
  s_right_jet:
    number: 23

virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4
  - s_trough5
  - s_trough6
  
keyboard:
  z:
    switch: s_left_flipper
  o:
    switch: s_right_flipper
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  6:
    switch: s_trough6
    toggle: true
  7:
    switch: s_trough_jam
  8:
    switch: s_plunger_lane
  9:
    switch: s_launch_button
  s:
    switch: s_start  
  i:
    switch: s_L_inlane 
    
coils:
  c_flipper_left_main:
    number: 0  # again, these numbers will probably be different for you
    default_pulse_ms: 20
  c_flipper_left_hold:
    number: 1  # check your platform-specific documentation for the actual numbers
    allow_enable: true
  c_flipper_right_main:
    number: 2
    default_pulse_ms: 20
  c_flipper_right_hold:
    number: 3
    allow_enable: true
  c_trough_eject:
    number: 4
  c_plunger:
    number: 5
    default_pulse_ms: 20
  c_top_popper:
    number: 6
  c_left_slingshot:
    number: 10
  c_right_slingshot:
    number: 11
  c_left_jet_bumper:
    number: 20
  c_right_jet_bumper:
    number: 21

ball_devices:
  bd_trough:
    ball_switches: s_trough1, s_trough2, s_trough3, s_trough4, s_trough5, s_trough6, s_trough_jam
    eject_coil: c_trough_eject
    tags: trough, home, drain
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    debug: true
    eject_targets: bd_plunger
  bd_plunger:
    ball_switches: s_plunger_lane
    eject_coil: c_plunger
    player_controlled_eject_event: s_launch_button_active
    eject_timeouts: 3s  
  bd_upper_vuk:
    ball_switches: s_top_popper
    eject_coil: c_top_popper
    eject_timeouts: 2s

autofire_coils:
  left_slingshot:
    coil: c_left_slingshot
    switch: s_left_slingshot
  right_slingshot:
    coil: c_right_slingshot
    switch: s_right_slingshot
  left_jet:
    coil: c_left_jet_bumper
    switch: s_left_jet
  right_jet:
    coil: c_right_jet_bumper
    switch: s_right_jet

playfields:
  playfield:
    tags: default
    default_source_device: bd_plunger

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper

lights:
  l_L_inlane:
   number:
  l_M_inlane:
   number:
  l_T_inlane:
   number: