#config_version=6

mode:
  start_events: ball_ending
  priority: 500
  use_wait_queue: true


mode_settings:
    bonus_entries:
        - entry: bonus_abc
          text: "Bonus ABC"
          player_score_entry: current_player.bonus_multiplier
          score: current_player.base_bonus
          reset_player_score_entry: true

  
slide_player:
  mode_bonus_started: bonus
  bonus_start:
    bonus:
      action: update
      tokens:
        entry: initial # display some initial text before the entry calculations are shown
  bonus_entry:
    bonus:
      action: update
   
# variable_player:
#   mode_bonus_will_stop:
#     base_bonus:
#       int: 0
#       action: set