#config_version=6

mode:
  start_events: start_mode_bonus
  stop_events: stop_mode_bonus
  priority: 50

mode_settings:
    bonus_entries:
        - entry: simple_bonus
          text: "Simple Bonus"
          player_score_entry: current_player.bonus_multiplier
          score: 1_000
          reset_player_score_entry: true

slide_player:
  mode_bonus_started: bonus
  bonus_start:
    bonus:
      action: update
      tokens:
        entry: initial # display some initial text before the entry calculations are shown
  bonus_entry:
    bonus:
      action: update
   