#config_version=6

mode:
  start_events: ball_ending
  priority: 500
  use_wait_queue: true


mode_settings:
    bonus_entries:
        - entry: simple_bonus
          text: "Simple Bonus"
          player_score_entry: current_player.bonus_multiplier
          score: 1_000
          reset_player_score_entry: true

### event players ####
## bonus lights
light_player:
  player_base_bonus{value == 1_000}:
    l_Led_Bonus_1: on
  player_base_bonus{value == 2_000}:
    l_Led_Bonus_2: on


  
slide_player:
  mode_bonus_started: bonus
  bonus_start:
    bonus:
      action: update
      tokens:
        entry: initial # display some initial text before the entry calculations are shown
  bonus_entry:
    bonus:
      action: update
   
variable_player:
  mode_bonus_will_stop:
    base_bonus:
      int: 0
      action: set