#config_version=6

coils:
    c_left_saucer:
       number: 0-0-1
       default_pulse_ms: 22
       default_pulse_power: 0.44
    c_right_sling:
       number: 0-0-2
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_recycle: True
       platform_settings:
            recycle_factor: 4
    c_left_sling:
       number: 0-0-3
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_recycle: True
       platform_settings:
            recycle_factor: 4
    c_right_bump:
       number: 0-0-4
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_recycle: True
       platform_settings:
            recycle_factor: 1
    c_left_bump:
       number: 0-0-5
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_recycle: True
       platform_settings:
            recycle_factor: 1
    c_bottom_bump:
       number: 0-0-6
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_recycle: True
       platform_settings:
            recycle_factor: 1
    c_outhole:
       number: 0-0-7
       default_pulse_ms: 22
       default_pulse_power: 0.55
       default_hold_power: 0.075
    c_flipper_left:
        number: 0-0-14
        allow_enable: true
        default_hold_power: 0.2
#!        default_pulse_power: 0.1
        default_pulse_ms: 35
    c_flipper_right:
        number: 0-0-13
        allow_enable: true
        default_hold_power: 0.2
#!        default_pulse_power: 0.54
        default_pulse_ms: 35
        
switches:
    #Cabinet Switches
   s_startButton:
      number: 0-0-16
      tags: start
      ignore_window_ms: 500ms 
   s_left_flipper:
      number: 0-0-17
      tags: left_flipper
   s_right_flipper:
      number: 0-0-18
      tags: right_flipper
    #Rapid Switches
   s_right_sling_spe:
      number: 0-0-27
   s_left_sling_spe:
      number: 0-0-26       
   s_right_bumper_spe:
      number: 0-0-25     
      tags: pops
   s_left_bumper_spe:
      number: 0-0-24      
      tags: pops
   s_bottom_bumper_spe:
      number: 0-0-19            
      tags: pops
    #Trough Switches
   s_outhole:
      number: 1-0-40
    #Playfield Switches
   s_left_outlane:
      number: 1-0-41
   s_d_rollover:
      number: 1-0-42
   s_left_kicker:
      number: 1-0-43
   s_lower_left_standup:
      number: 1-0-44
   s_1_target:
      number: 1-0-45
   s_eject_hole:
      number: 1-0-46
   s_middle_left_standup:
      number: 1-0-47
   s_upper_left_standup:
      number: 1-0-48
   s_g_drop_target:
      number: 1-0-49
   s_o_drop_target:
      number: 1-0-50
   s_r_drop_target:
      number: 1-0-51
   s_gor_drop_targets_series:
      number: 1-0-52
   s_gor_drop_target_Standup:
      number: 1-0-53
   s_magnet_switch:
      number: 1-0-54
   s_middle_lower_standup:
      number: 1-0-55
   s_middle_upper_standup:
      number: 1-0-56
   s_a_rollover:
      number: 1-0-57
   s_b_rollover:
      number: 1-0-58
   s_c_rollover:
      number: 1-0-59
   s_playfield_tilt:
      number: 1-0-60
   s_spinner:
      number: 1-0-61
   s_2_target:
      number: 1-0-62
   s_3_target:
      number: 1-0-63
   s_4_target:
      number: 1-0-64
   s_right_outlane:
      number: 1-0-65
   s_e_rollover:
      number: 1-0-66
   s_right_kicker:
      number: 1-0-67
   s_left_bumper:
      number: 1-0-68
   s_top_bumper:
      number: 1-0-69
   s_bottom_bumper:
      number: 1-0-70
   s_gar_drop_targets_standup:
      number: 1-0-71
   s_g2_drop_target:
      number: 1-0-72
   s_a_drop_target:
      number: 1-0-73
   s_r2_drop_target:
      number: 1-0-74
   s_gar_drop_targets_series:
      number: 1-0-75
      
flippers:
  left_flipper:
        main_coil: c_flipper_left
        activation_switch: s_left_flipper
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown
  right_flipper:
        main_coil: c_flipper_right
        activation_switch: s_right_flipper
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown

autofire_coils:
    slingshot_left:
        coil: c_left_sling
        switch: s_left_sling_spe
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown
    slingshot_right:
        coil: c_right_sling
        switch: s_right_sling_spe
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown
    pop_left:
        coil: c_left_bump
        switch: s_left_bumper_spe
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown
    pop_right:
        coil: c_right_bump
        switch: s_right_bumper_spe
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown
    pop_lower:
        coil: c_bottom_bump
        switch: s_bottom_bumper_spe
        enable_events: ball_started, enableAutofire
        disable_events: ball_will_end, disableAutofire, shutdown

lights:
    l_Led_C:
        number: 0-0-0
        type: grb
        subtype: led
        tags: inserts
    l_Led_B:
        previous: l_Led_C #number: 0-0-0
        type: grb
        subtype: led
        tags: inserts
    l_Led_A:
        previous: l_Led_B #number: 0-0-1
        type: grb
        subtype: led
        tags: inserts
    l_Led_Mag_50_000:
        previous: l_Led_A #number: 0-0-2
        type: grb
        subtype: led
        tags: inserts
    l_Led_Mag_30_000:
        previous: l_Led_Mag_50_000 #number: 0-0-3
        type: grb
        subtype: led
        tags: inserts
    l_Led_Mag_20_000:
        previous: l_Led_Mag_30_000 #number: 0-0-4
        type: grb
        subtype: led
        tags: inserts
    l_Led_Mag_10_000:
        previous: l_Led_Mag_20_000 #number: 0-0-5
        type: grb
        subtype: led
        tags: inserts
    l_Led_Mag_5_000:
        previous: l_Led_Mag_10_000 #number: 0-0-6
        type: grb
        subtype: led
        tags: inserts
    l_Led_Upper_Gor:
        previous: l_Led_Mag_5_000 #number: 0-0-7
        type: grb
        subtype: led
        tags: inserts
    l_Led_Lower_Gor:
        previous: l_Led_Upper_Gor #number: 0-0-8
        type: grb
        subtype: led
        tags: inserts
    l_Led_WLit_5_000:
        previous: l_Led_Lower_Gor #number: 0-0-9
        type: grb
        subtype: led
        tags: inserts
    l_Led_Hole_ExBall:
        previous: l_Led_WLit_5_000 #number: 0-0-10
        type: grb
        subtype: led
        tags: inserts
    l_Led_Hole_15_000:
        previous: l_Led_Hole_ExBall #number: 0-0-11
        type: grb
        subtype: led
        tags: inserts
    l_Led_Hole_10_000:
        previous: l_Led_Hole_15_000 #number: 0-0-12
        type: grb
        subtype: led
        tags: inserts
    l_Led_Target_1:
        previous: l_Led_Hole_10_000 #number: 0-0-13
        type: grb
        subtype: led
        tags: inserts
    l_Led_Target_1_Red_Arrow:
        previous: l_Led_Target_1 #number: 0-0-14
        type: grb
        subtype: led
        tags: inserts
    l_Led_Special_Left:
        previous: l_Led_Target_1_Red_Arrow #number: 0-0-15
        type: grb
        subtype: led
        tags: inserts
    l_Led_Inlane_D:
        previous: l_Led_Special_Left #number: 0-0-16
        type: grb
        subtype: led
        tags: inserts
    l_Led_2X:
        previous: l_Led_Inlane_D #number: 0-0-17
        type: grb
        subtype: led
        tags: inserts
    l_Led_3X:
        previous: l_Led_2X #number: 0-0-18
        type: grb
        subtype: led
        tags: inserts
    l_Led_Bonus_1:
        previous: l_Led_3X #number: 0-0-19
        type: grb
        subtype: led
        tags: inserts, inserts_bonus
    l_Led_Bonus_2:
        previous: l_Led_Bonus_1 #number: 0-0-20
        type: grb
        subtype: led
        tags: inserts, inserts_bonus
    l_Led_Bonus_3:
        previous: l_Led_Bonus_2 #number: 0-0-21
        type: grb
        subtype: led
        tags: inserts, inserts_bonus
    l_Led_Bonus_4:
        previous: l_Led_Bonus_3 #number: 0-0-22
        type: grb
        subtype: led
        tags: inserts, inserts_bonus
    l_Led_Bonus_20:
        previous: l_Led_Bonus_4 #number: 0-0-23
        type: grb
        subtype: led
        tags: inserts, inserts_bonus
    l_Led_Bonus_5:
        previous: l_Led_Bonus_20 #number: 0-0-24
        type: grb
        subtype: led
        tags: inserts, inserts_bonus
    l_Led_Bonus_6:
        previous: l_Led_Bonus_5 #number: 0-0-25
        type: grb
        subtype: led
        tags: inserts, inserts_bonus 
    l_Led_Bonus_7:
        previous: l_Led_Bonus_6 #number: 0-0-26
        type: grb
        subtype: led
        tags: inserts, inserts_bonus  
    l_Led_Bonus_8:
        previous: l_Led_Bonus_7 #number: 0-0-27
        type: grb
        subtype: led
        tags: inserts, inserts_bonus  
    l_Led_Bonus_9:
        previous: l_Led_Bonus_8 #number: 0-0-28
        type: grb
        subtype: led
        tags: inserts, inserts_bonus  
    l_Led_Bonus_10:
        previous: l_Led_Bonus_9 #number: 0-0-29
        type: grb
        subtype: led
        tags: inserts, inserts_bonus  
    l_Led_Star_1:
        previous: l_Led_Bonus_10 #number: 0-0-30
        type: grb
        subtype: led
        tags: inserts, inserts_bonus  
    l_Led_Shoot_Again:
        previous: l_Led_Star_1 #number: 0-0-31
        type: grb
        subtype: led
        tags: inserts  
    l_Led_Star_2:
        previous: l_Led_Shoot_Again #number: 0-0-32
        type: grb
        subtype: led
        tags: inserts      
    l_Led_Inlane_E:
        previous: l_Led_Star_2 #number: 0-0-33
        type: grb
        subtype: led
        tags: inserts   
    l_Led_Special_Right:
        previous: l_Led_Inlane_E #number: 0-0-34
        type: grb
        subtype: led
        tags: inserts 
    l_Led_Arrow_Target_4:
        previous: l_Led_Special_Right #number: 0-0-35
        type: grb
        subtype: led
        tags: inserts 
    l_Led_Target_4:
        previous: l_Led_Arrow_Target_4 #number: 0-0-36
        type: grb
        subtype: led
        tags: inserts 
    l_Led_Arrow_Target_3:
        previous: l_Led_Target_4 #number: 0-0-37
        type: grb
        subtype: led
        tags: inserts 
    l_Led_Target_3:
        previous: l_Led_Arrow_Target_3 #number: 0-0-38
        type: grb
        subtype: led
        tags: inserts 
    l_Led_Arrow_Target_2:
        previous: l_Led_Target_3 #number: 0-0-39
        type: grb
        subtype: led
        tags: inserts 
    l_Led_Target_2:
        previous: l_Led_Arrow_Target_2 #number: 0-0-40
        type: grb
        subtype: led
        tags: inserts 
    l_Led_Spinner_1000:
        previous: l_Led_Target_2 #number: 0-0-41
        type: grb
        subtype: led
        tags: inserts 
light_player:
   led_code:
      inserts: FFFFFF
   led_off:
      inserts: off
   led_name:
      inserts: LightSalmon
   group_light:
      inserts: green
   led_fade:
      inserts:
        color: slateblue
        fade: 2000ms

# keyboard:
#    1:
#      event: led_off
#    2:
#      event: led_code
#    3:
#      event: led_name
#    4:
#      event: group_light
#    5:
#      event: led_fade
     
ball_devices:
    bd_trough:
        ball_switches: s_outhole
        eject_coil: c_outhole
        tags: trough, home, drain, home
        eject_coil_jam_pulse: 15ms
        debug: true
    bd_leftSaucer:
        ball_switches: s_eject_hole
        eject_coil: c_left_saucer
        eject_timeouts: 1s
        entrance_count_delay: 900ms
            
playfields:
  playfield:
    tags: default
    default_source_device: bd_trough
    enable_ball_search: True
    ball_search_timeout: 45s
    ball_search_wait_after_iteration: 30s
    ball_search_interval: 250ms

# virtual_platform_start_active_switches:
#     - s_outhole

machine:
    balls_installed: 1

game:
    balls_per_game: 3
    max_players: 4