#config_version=6

mode:
  start_events: start_mode_hurryup
  stop_events: stop_mode_hurryup
  priority: 1000

event_player:
  timer_hurryup_timer_complete : stop_mode_hurryup
  hurryup_OK_hit: stop_mode_hurryup
  timer_hurryup_timer_tick:
    hurryup_value:
      current_hurryup:
        type: int
        value: 100_000 - ticks * 2_000

timers:
  hurryup_timer:
    end_value: 50
    start_running: true
    tick_interval: 200ms

shots:
  hurryup_OK:
    switch: s_2_target

slide_player:
   mode_hurryup_started: hurryup
   

variable_player:
  hurryup_OK_hit:
    score: 100_000 - device.timers.hurryup_timer.ticks * 2_000